query Petitions($search: String, $region: RegionInput, $limit: Int, $offset: Int, $userId: ModelID) {
    petitions(search: $search, region: $region, limit: $limit, offset: $offset, userId: $userId) {
        ...PetitionFields
    }
}
