fragment PetitionFields on Petition {
    id
    title
    description
    numberOfVotes
    latitude
    longitude
    address
    city
    state
    country
    postalCode
    createdAt
    updatedAt
    userId
    mediaFiles {
        ...MediaFileFields
    }
}
